### ISSUE TITLE
Comaptibility with 5.x

### ISSUE THREAD

**Issue by roshanroche** [tpartner/LimeSurvey-5-Point-Emojis#1]
Hi 

is this compatible with lime survey 5.x

**Comment by tpartner** [comment]
Not tested yet.

**Comment by roshanroche** [comment]
Hi @tpartner any chance there will be a release for 5.x version ?

**Comment by tpartner** [comment]
When time allows.

**Comment by tpartner** [comment]
Should be good now.

**Comment by roshanroche** [comment]
Hi @tpartner Thanks for the update.. i really appreciate it.

i tried with importing the zip file. however i get the following error

![image](https://user-images.githubusercontent.com/22425503/127185940-e573706e-86ba-455f-a443-10b984f7d034.png)

when i copy the folder under upload/themes

i dont get the emoji option under 5 point question

![image](https://user-images.githubusercontent.com/22425503/127186186-e6f23321-66ba-49c5-8dfb-7397491c0a0f.png)

what could be wrong?

**Comment by tpartner** [comment]
This is not an issue with the question theme. Ask in the LimeSurvey forums.
