### ISSUE TITLE
Issue on Import

### ISSUE THREAD

**Issue by MartinIsOnGithub** [tpartner/LimeSurvey-5-Point-Emojis#2]
Hi, I am using limesurvey. I just made an account last week, so I should be on the latest version, but also after googling I have not found how to find the version on a lime-survey hosted version. 

Anyhow, I tried your code (thanks btw). I followed the steps with unzipping and zipping but on uploading I get this error: 

500: Internal Server Error
Error: Can't find a manifest for LS3-TFR-theme01 in ' /limeservice/instances/5/limesurvey/themes/survey/LS3-TFR-theme01/ ' 

Thanks for your help 
Martin

**Comment by tpartner** [comment]
It looks to me like you have a problem with a survey theme, not a question theme.

Also  ensure that you are in the "Question" tab of the themes interface when uploading/importing question themes.
