### ISSUE TITLE
optional custum options

### ISSUE THREAD

**Issue by TobiasCasag** [tpartner/LimeSurvey-5-Point-Emojis#4]
Could you add an option "Adjust the settings in the "Custom options" question attributes." like in NPS, and an easy way to change the pictures of the emojis so that it could fit to a custom CI/CD

best regards Tobias

**Comment by tpartner** [comment]
This question theme is pure CSS. There are no images for the emojis - the browser renders those.

**Comment by TobiasCasag** [comment]
thanks for your fast reply / so its the font which is responsible for the emojis - but i would be more interested in the custom options with the possibility to add some text like putting a help text like at the NPS feature -> very unlikely |  sehr unwahrscheinlich vs.  very likely | sehr wahrscheinlich, here "not stisfied at all"  to "sehr zufrieden | very satisfied"

![image](https://github.com/tpartner/LimeSurvey-5-Point-Emojis/assets/167329570/b0a7cbd4-ffa8-4a8b-8f0d-0b63c937c612)

**Comment by tpartner** [comment]
I don't see this as an "issue", it is a feature request. I suppose that could be added but I don't currently have time.

**Comment by TobiasCasag** [comment]
yes you are right - it is a feature request - i am new on github, i didnt know how to get in contact - sorry.
